# Generated by Django 6.0.6 on 2026-06-18 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('role', models.CharField(choices=[('academic facilitator', 'Academic Facilitator'), ('head of school', 'Head of School'), ('director', 'Director')], max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('croissant', 'Croissant')], default='other', null=True)),
                ('date_of_birth', models.DateField(auto_now_add=True, null=True)),
                ('nationality', models.CharField(choices=[('chinese', 'Chinese'), ('canadian', 'Canadian'), ('mexican', 'Mexican'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('ghanaian', 'Ghanaian')], null=True)),
                ('address', models.TextField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=555, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255, null=True)),
                ('level', models.CharField(choices=[('easy', 'Easy'), ('intermediate', 'Intermediate'), ('hard', 'Hard'), ('extreme', 'Extreme')], max_length=255, null=True)),
                ('academic_year', models.CharField(max_length=255, null=True)),
                ('capacity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Academic_Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_school', models.CharField(max_length=255, null=True)),
                ('last_class_completed', models.IntegerField(null=True)),
                ('grade', models.IntegerField(max_length=3, null=True)),
                ('completion_year', models.IntegerField(null=True)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.applicants')),
            ],
        ),
        migrations.CreateModel(
            name='Guardians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('relatinship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian')], default='guardian', null=True)),
                ('phone_number', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=555, null=True)),
                ('address', models.TextField(max_length=255, null=True)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.applicants')),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_number', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending'), ('denied', 'Denied')], max_length=255, null=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('review_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.applicants')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.admin')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.programs')),
            ],
        ),
    ]
