# Generated by Django 6.0.6 on 2026-06-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardians',
            old_name='relatinship',
            new_name='relationship',
        ),
        migrations.AlterField(
            model_name='academic_records',
            name='grade',
            field=models.IntegerField(null=True),
        ),
    ]
